paths:
  raw_data_dir: data/ECG5000
  raw_train_file: ECG5000_TRAIN.txt
  raw_test_file: ECG5000_TEST.txt
  processed_data_dir: data/processed
  models_dir: models
  reports_dir: reports

models:
  random_forest:
    module: models.baseline
    fit_function: fit_baseline_model
    artifact_name: baseline_random_forest.joblib
    random_state: 42

  logistic_regression:
    module: models.logistic_baseline
    fit_function: fit_logistic_model
    artifact_name: logistic_regression.joblib
    random_state: 42

  lstm:
    module: models.LSTM
    fit_function: fit_lstm_model
    artifact_name: lstm.joblib
    random_state: 42
    fit_params:
      loss_weights: [0.004,0.038,0.02,0.354,0.584]
      epochs: 500
      batch_size: 2084
      learning_rate: 0.001
      use_scaling: true
      hidden_size: 64
      n_layers: 1

  transformer:
    module: models.encoder
    fit_function: fit_transformer
    artifact_name: trasnformer.joblib
    random_state: 42
    fit_params:
        loss_weights: [0.2,0.2,0.2,0.2,0.2]
        epochs: 200
        input_size: 1
        batch_size: 2084
        learning_rate: 0.001
        use_scaling: True
        d_model: 64
        dim_ff: 128
        n_heads: 4
        n_layers: 2

  xlstm:
    module: models.xLSTM
    fit_function: fit_xlstm
    artifact_name: xlstm.joblib
    random_state: 42
    fit_params:
      loss_weights: [ 0.2,0.2,0.2,0.2,0.2 ]
      epochs: 200
      input_size: 1
      batch_size: 2084
      learning_rate: 0.001
      use_scaling: True
      d_model: 64
      n_blocks: 2     # set to 2 or more for xLSTM with mLSTM and sLSTM block
      n_heads: 4
      conv1d_kernel_size: 4
      qkv_proj_blocksize: 4

training:
  selected_model: lstm
  validation_from_test_fraction: 0
